package com.cristian.engage.entities;

// Generated May 23, 2014 7:42:18 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name = "action")
public class ActionEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String operation;
	private String params;
	private List<MacroEntity> macros = new ArrayList<MacroEntity>();

	public ActionEntity() {
	}

	public ActionEntity(String operation, String params) {
		this.operation = operation;
		this.params = params;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "operation", length = 45)
	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	@Column(name = "params", length = 1)
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "macro_has_action", joinColumns = { @JoinColumn(name = "action_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "macro_id", nullable = false, updatable = false) })
	public List<MacroEntity> getMacros() {
		return this.macros;
	}

	public void setMacros(List<MacroEntity> macros) {
		this.macros = macros;
	}

	@Override
	public String toString() {
		return "ActionEntity [id=" + id + ", operation=" + operation + ", params=" + params + ", macros=" + macros
				+ "]";
	}
	
}
